export const quizData = [
  {
    command: "sudo [command]",
    description: "run <command> in superuser mode",
    dummyAnswer1: "run <command> without root permissions",
    dummyAnswer2: "open a new terminal session",
  },
  {
    command: "nohup [command]",
    description: "run <command> immune to hangup signal",
    dummyAnswer1: "run <command> as a background process",
    dummyAnswer2: "run <command> with high priority",
  },
  {
    command: "man [command]",
    description: "display help pages of <command>",
    dummyAnswer1: "display version of <command>",
    dummyAnswer2: "execute <command>",
  },
  {
    command: "[command] &",
    description: "run <command> and send task to background",
    dummyAnswer1: "run <command> in superuser mode",
    dummyAnswer2: "run <command> and terminate after completion",
  },
  {
    command: ">> [fileA]",
    description: "append to fileA, preserving existing contents",
    dummyAnswer1: "overwrite fileA with new content",
    dummyAnswer2: "create a new file named fileA",
  },
  {
    command: "> [fileA]",
    description: "output to fileA, overwriting contents",
    dummyAnswer1: "append to fileA, preserving existing contents",
    dummyAnswer2: "delete fileA",
  },
  {
    command: "echo -n",
    description: "display a line of text",
    dummyAnswer1: "display system information",
    dummyAnswer2: "list directory contents",
  },
  {
    command: "xargs",
    description: "build command line from previous output",
    dummyAnswer1: "display arguments of previous command",
    dummyAnswer2: "execute commands from a file",
  },
  {
    command: "1>2&",
    description: "Redirect stdout to stderr",
    dummyAnswer1: "Redirect stderr to a file",
    dummyAnswer2: "Redirect stdout to a file",
  },
  {
    command: "fg %N",
    description: "go to task N",
    dummyAnswer1: "kill task N",
    dummyAnswer2: "list all tasks",
  },
  {
    command: "jobs",
    description: "list task",
    dummyAnswer1: "start a new task",
    dummyAnswer2: "display system logs",
  },
  {
    command: "ctrl-z",
    description: "suspend current task",
    dummyAnswer1: "terminate current task",
    dummyAnswer2: "switch to previous task",
  },
  {
    command: "df -h, -i",
    description: "File system usage",
    dummyAnswer1: "display disk free space in megabytes",
    dummyAnswer2: "format the disk",
  },
  {
    command: "mkfs -t -V",
    description: "create file system",
    dummyAnswer1: "check file system integrity",
    dummyAnswer2: "list file system types",
  },
  {
    command: "resize2fs",
    description: "update a filesystem, after lvextend*",
    dummyAnswer1: "create a new filesystem",
    dummyAnswer2: "delete an existing filesystem",
  },
  {
    command: "fsck -A -N",
    description: "file system check & repair",
    dummyAnswer1: "update the file system",
    dummyAnswer2: "display file system usage",
  },
  {
    command: "pvcreate",
    description: "create physical volume",
    dummyAnswer1: "delete physical volume",
    dummyAnswer2: "list physical volumes",
  },
  {
    command: "mount -a -t",
    description: "mount a filesystem",
    dummyAnswer1: "unmount a filesystem",
    dummyAnswer2: "list all mounted filesystems",
  },
  {
    command: "fdisk -l",
    description: "edit disk partition",
    dummyAnswer1: "format disk partition",
    dummyAnswer2: "list disk usage",
  },
  {
    command: "lvcreate",
    description: "create a logical volume",
    dummyAnswer1: "delete a logical volume",
    dummyAnswer2: "list logical volumes",
  },
  {
    command: "umount -f -v",
    description: "umount a filesystem",
    dummyAnswer1: "force mount a filesystem",
    dummyAnswer2: "check filesystem status",
  },
  {
    command: "chmod -c -R",
    description: "chmod file read, write and executable permission",
    dummyAnswer1: "change file owner",
    dummyAnswer2: "create a new file",
  },
  {
    command: "touch -a -t",
    description: "modify (or create) file timestamp",
    dummyAnswer1: "change file permissions",
    dummyAnswer2: "delete a file",
  },
  {
    command: "chown -c -R",
    description: "change file ownership",
    dummyAnswer1: "change file group",
    dummyAnswer2: "display file content",
  },
  {
    command: "chgrp -c -R",
    description: "change file group permission",
    dummyAnswer1: "change file owner",
    dummyAnswer2: "list files in a directory",
  },
  {
    command: "tr -d",
    description: "translate or delete character",
    dummyAnswer1: "find and replace text",
    dummyAnswer2: "sort lines of text",
  },
  {
    command: "uniq -c -u",
    description: "report or omit repeated lines",
    dummyAnswer1: "find unique lines in a file",
    dummyAnswer2: "sort lines of text",
  },
  {
    command: "split -l",
    description: "split file into pieces",
    dummyAnswer1: "combine multiple files",
    dummyAnswer2: "delete multiple files",
  },
  {
    command: "wc -w",
    description: "print newline, word, and byte counts for each file",
    dummyAnswer1: "count number of lines in a file",
    dummyAnswer2: "display file content",
  },
  {
    command: "head -n",
    description: "output the first part of files",
    dummyAnswer1: "output the last part of files",
    dummyAnswer2: "display file content",
  },
  {
    command: "cut -s",
    description: "remove section from file",
    dummyAnswer1: "add a section to a file",
    dummyAnswer2: "sort lines of text",
  },
  {
    command: "diff -q",
    description: "file compare, line by line",
    dummyAnswer1: "combine two files",
    dummyAnswer2: "delete duplicate lines",
  },
  {
    command: "join -i",
    description: "join lines of two files on a common field",
    dummyAnswer1: "split file into pieces",
    dummyAnswer2: "find unique lines in a file",
  },
  {
    command: "more, less",
    description: "view file content, one page at a time",
    dummyAnswer1: "edit file content",
    dummyAnswer2: "delete file content",
  },
  {
    command: "sort -n",
    description: "sort lines in text file",
    dummyAnswer1: "combine multiple text files",
    dummyAnswer2: "split text file into sections",
  },
  {
    command: "comm -3",
    description: "compare two sorted files, line by line",
    dummyAnswer1: "combine two sorted files",
    dummyAnswer2: "sort lines in text file",
  },
  {
    command: "cat -s",
    description: "concatenate files to the standard output",
    dummyAnswer1: "copy files to a directory",
    dummyAnswer2: "delete files",
  },
  {
    command: "tail -f",
    description: "output last part of the file",
    dummyAnswer1: "output first part of the file",
    dummyAnswer2: "display file size",
  },
  {
    command: "mkdir",
    description: "create a directory",
    dummyAnswer1: "remove a directory",
    dummyAnswer2: "list contents of a directory",
  },
  {
    command: "rmdir",
    description: "remove a directory",
    dummyAnswer1: "create a directory",
    dummyAnswer2: "change directory",
  },
  {
    command: "find",
    description: "search for a file",
    dummyAnswer1: "delete a file",
    dummyAnswer2: "copy a file",
  },
  {
    command: "ls -a -C -h",
    description: "list content of directory",
    dummyAnswer1: "change file permissions",
    dummyAnswer2: "create a new file",
  },
  {
    command: "rm -r -f",
    description: "remove files and directory",
    dummyAnswer1: "move files and directory",
    dummyAnswer2: "create files and directory",
  },
  {
    command: "locate -i",
    description: "find file, using updatedb(8) database",
    dummyAnswer1: "delete file",
    dummyAnswer2: "create a new file",
  },
  {
    command: "cp -a -R -i",
    description: "copy files or directory",
    dummyAnswer1: "delete files or directory",
    dummyAnswer2: "move files or directory",
  },
  {
    command: "du -s",
    description: "disk usage",
    dummyAnswer1: "display file system information",
    dummyAnswer2: "check disk for errors",
  },
  {
    command: "file -b -i",
    description: "identify the file type",
    dummyAnswer1: "delete the file",
    dummyAnswer2: "change file permissions",
  },
  {
    command: "mv -f -i",
    description: "move files or directory",
    dummyAnswer1: "copy files or directory",
    dummyAnswer2: "create files or directory",
  },
  {
    command: "grep, egrep, fgrep -i -v",
    description: "print lines matching pattern",
    dummyAnswer1: "delete lines matching pattern",
    dummyAnswer2: "sort lines matching pattern",
  },
  {
    command: "tar xvfz",
    description: "create or extract .tar or .tgz files",
    dummyAnswer1: "compress .tar or .tgz files",
    dummyAnswer2: "delete .tar or .tgz files",
  },
  {
    command: "gzip, gunzip, zcat",
    description: "create, extract or view .gz files",
    dummyAnswer1: "compress, extract or view .zip files",
    dummyAnswer2: "delete .gz files",
  },
  {
    command: "uuencode, uudecode",
    description: "create or extract .Z files",
    dummyAnswer1: "compress or extract .tar files",
    dummyAnswer2: "create or extract .gz files",
  },
  {
    command: "zip, unzip -v",
    description: "create or extract .ZIP files",
    dummyAnswer1: "create or extract .tar files",
    dummyAnswer2: "delete .ZIP files",
  },
  {
    command: "rpm",
    description: "create or extract .rpm files",
    dummyAnswer1: "create or extract .tar files",
    dummyAnswer2: "delete .rpm files",
  },
  {
    command: "bzip2, bunzip2",
    description: "create or extract .bz2 files",
    dummyAnswer1: "create or extract .zip files",
    dummyAnswer2: "delete .bz2 files",
  },
  {
    command: "rar",
    description: "create or extract .rar files",
    dummyAnswer1: "create or extract .zip files",
    dummyAnswer2: "delete .rar files",
  },
  {
    command: "ex",
    description: "basic editor",
    dummyAnswer1: "advanced editor",
    dummyAnswer2: "system monitor",
  },
  {
    command: "vi",
    description: "visual editor",
    dummyAnswer1: "basic editor",
    dummyAnswer2: "file manager",
  },
  {
    command: "nano",
    description: "pico clone",
    dummyAnswer1: "text-based web browser",
    dummyAnswer2: "system monitor",
  },
  {
    command: "view",
    description: "view file only",
    dummyAnswer1: "edit file",
    dummyAnswer2: "delete file",
  },
  {
    command: "emacs",
    description: "extensible, customizable editor",
    dummyAnswer1: "system monitor",
    dummyAnswer2: "advanced text-based web browser",
  },
];
